### ISSUE TITLE
[Roadmap] Donation Options

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/humhub-pledge-module#1]
### Donation Options
List of donation options.
- [ ] Implement [Patreon](https://github.com/GreenMeteor/humhub-patreon-module)
- [ ] Implement [Ko-fi](https://github.com/GreenMeteor/humhub-ko_fi-module)
- [ ] Implement [PayPal](https://paypal.com/)
- [ ] Implement [SubscriberStar](https://www.subscribestar.com/)
> TBA
### Translations
List of translations needed done.
> TBA
